version: 2

models:
  - name: date
    description: "dimension table of date"
    columns:
      - name: date_sk
        description: "The surrogate key for the date dimension"
        tests:
          - unique
          - not_null