version: 2

models:
  - name: date
    description: "dimension table of date"
    columns:
      - name: date_sk
        description: "The surrogate key for the date dimension"
        tests:
          - unique
          - not_null
      - name: date
        description: "The date formatted as a date"
        tests:
          - not_null

  - name: location
    description: "dimension table of location"
    columns:
      - name: location_sk
        description: "The surrogate key for the location dimension"
        tests:
          - unique
          - not_null
      - name: location_iso_code
        description: "The ISO code for the location"
        tests:
          - not_null
      - name: latitude
        description: "The latitude of the location"
        tests:
          - not_null
      - name: longitude
        description: "The longitude of the location"
        tests:
          - not_null
      - name: location
        description: "The name of the location"
        tests:
          - not_null

  - name: covid_stats
    description: "fact table of covid-19 cases, deaths, recoveries, etc. It has additive, semi-additive and non-additive facts"
    columns:
      - name: date_sk
        description: "The foreign key referencing the date dimension"
        tests:
          - not_null
          - relationships:
              to: ref('date')
              field: date_sk
      - name: location_sk
        description: "The foreign key referencing the location dimension"
        tests:
          - not_null
          - relationships:
              to: ref('location')
              field: location_sk